// Code generated by github.com/citradigital/protonats. DO NOT EDIT.
// package: cdl.protonats
// source: nats_test.proto
package test

import (
	"github.com/citradigital/protonats"
	context "golang.org/x/net/context"
)


type TestServiceGRPC struct {
	Context context.Context
	Bus     *protonats.Bus
	Service *TestServiceProtonatsClient
}

func NewTestServiceGRPC(ctx context.Context, config protonats.ServiceConfiguration) (*TestServiceGRPC, error) {
	client, err := protonats.NewBus(ctx, config)
	if err != nil {
		return nil, err
	}

	service := TestServiceGRPC{
		Context: ctx,
		Bus:     client,
		Service: NewTestServiceProtonatsClient(client),
	}

	return &service, nil
}

func (svc *TestServiceGRPC) Close() {
	svc.Bus.Close()
}

	

func (svc *TestServiceGRPC) GetTestA(ctx context.Context, req *TestARequest) (*TestAResponse, error) {
	return svc.Service.GetTestA(ctx, req)
}

	

	




