// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: toldata_test.proto

package test

import (
	context "context"
	fmt "fmt"
	toldata "github.com/citradigital/toldata"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TestARequest struct {
	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *TestARequest) Reset()         { *m = TestARequest{} }
func (m *TestARequest) String() string { return proto.CompactTextString(m) }
func (*TestARequest) ProtoMessage()    {}
func (*TestARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{0}
}
func (m *TestARequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestARequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestARequest.Merge(m, src)
}
func (m *TestARequest) XXX_Size() int {
	return m.Size()
}
func (m *TestARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestARequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestARequest proto.InternalMessageInfo

func (m *TestARequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *TestARequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TestAResponse struct {
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Id     int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *TestAResponse) Reset()         { *m = TestAResponse{} }
func (m *TestAResponse) String() string { return proto.CompactTextString(m) }
func (*TestAResponse) ProtoMessage()    {}
func (*TestAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{1}
}
func (m *TestAResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestAResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAResponse.Merge(m, src)
}
func (m *TestAResponse) XXX_Size() int {
	return m.Size()
}
func (m *TestAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestAResponse proto.InternalMessageInfo

func (m *TestAResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *TestAResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FeedDataRequest struct {
	Data int64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *FeedDataRequest) Reset()         { *m = FeedDataRequest{} }
func (m *FeedDataRequest) String() string { return proto.CompactTextString(m) }
func (*FeedDataRequest) ProtoMessage()    {}
func (*FeedDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{2}
}
func (m *FeedDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedDataRequest.Merge(m, src)
}
func (m *FeedDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *FeedDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedDataRequest proto.InternalMessageInfo

func (m *FeedDataRequest) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type FeedDataResponse struct {
	Sum int64 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (m *FeedDataResponse) Reset()         { *m = FeedDataResponse{} }
func (m *FeedDataResponse) String() string { return proto.CompactTextString(m) }
func (*FeedDataResponse) ProtoMessage()    {}
func (*FeedDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{3}
}
func (m *FeedDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedDataResponse.Merge(m, src)
}
func (m *FeedDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *FeedDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedDataResponse proto.InternalMessageInfo

func (m *FeedDataResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type StreamDataRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *StreamDataRequest) Reset()         { *m = StreamDataRequest{} }
func (m *StreamDataRequest) String() string { return proto.CompactTextString(m) }
func (*StreamDataRequest) ProtoMessage()    {}
func (*StreamDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{4}
}
func (m *StreamDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamDataRequest.Merge(m, src)
}
func (m *StreamDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *StreamDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamDataRequest proto.InternalMessageInfo

func (m *StreamDataRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StreamDataResponse struct {
	Data int64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *StreamDataResponse) Reset()         { *m = StreamDataResponse{} }
func (m *StreamDataResponse) String() string { return proto.CompactTextString(m) }
func (*StreamDataResponse) ProtoMessage()    {}
func (*StreamDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba7b1d9bf4c039b, []int{5}
}
func (m *StreamDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamDataResponse.Merge(m, src)
}
func (m *StreamDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *StreamDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamDataResponse proto.InternalMessageInfo

func (m *StreamDataResponse) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

var E_RestMount = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         99999,
	Name:          "cdl.toldatatest.rest_mount",
	Tag:           "bytes,99999,opt,name=rest_mount",
	Filename:      "toldata_test.proto",
}

func init() {
	proto.RegisterType((*TestARequest)(nil), "cdl.toldatatest.TestARequest")
	proto.RegisterType((*TestAResponse)(nil), "cdl.toldatatest.TestAResponse")
	proto.RegisterType((*FeedDataRequest)(nil), "cdl.toldatatest.FeedDataRequest")
	proto.RegisterType((*FeedDataResponse)(nil), "cdl.toldatatest.FeedDataResponse")
	proto.RegisterType((*StreamDataRequest)(nil), "cdl.toldatatest.StreamDataRequest")
	proto.RegisterType((*StreamDataResponse)(nil), "cdl.toldatatest.StreamDataResponse")
	proto.RegisterExtension(E_RestMount)
}

func init() { proto.RegisterFile("toldata_test.proto", fileDescriptor_1ba7b1d9bf4c039b) }

var fileDescriptor_1ba7b1d9bf4c039b = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xcf, 0xb4, 0x6b, 0xd9, 0x3c, 0xdd, 0x3f, 0x3e, 0x44, 0x4a, 0xc0, 0x58, 0xb3, 0x0a, 0xbd,
	0x38, 0x59, 0xff, 0x21, 0x78, 0x72, 0x17, 0xff, 0x1c, 0x54, 0x84, 0xd6, 0x8b, 0x82, 0x2c, 0x69,
	0x32, 0xd6, 0x81, 0xa4, 0x13, 0x33, 0x2f, 0x82, 0x1f, 0x42, 0xf0, 0x1b, 0xf8, 0x75, 0x3c, 0xee,
	0xd1, 0xa3, 0xb4, 0x27, 0xbf, 0x82, 0x20, 0xc8, 0x24, 0x13, 0x5b, 0x36, 0x6b, 0x2f, 0xee, 0x29,
	0xf3, 0xde, 0xfc, 0xfe, 0x64, 0x7e, 0x33, 0x0f, 0x90, 0x54, 0x9a, 0x44, 0x14, 0x1d, 0x91, 0xd0,
	0xc4, 0xf3, 0x42, 0x91, 0xc2, 0x9d, 0x38, 0x49, 0xb9, 0xed, 0x9b, 0xb6, 0x77, 0x73, 0x2a, 0xe9,
	0x7d, 0x39, 0xe1, 0xb1, 0xca, 0xc2, 0x58, 0x52, 0x11, 0x25, 0x72, 0x2a, 0x29, 0x4a, 0x43, 0x0b,
	0x6a, 0xbe, 0x35, 0xdf, 0x1b, 0x4c, 0x95, 0x9a, 0xa6, 0x22, 0xac, 0xaa, 0x49, 0xf9, 0x2e, 0x4c,
	0x84, 0x8e, 0x0b, 0x99, 0x93, 0x2a, 0x6a, 0x44, 0x70, 0x17, 0x2e, 0xbc, 0x12, 0x9a, 0x0e, 0x46,
	0xe2, 0x43, 0x29, 0x34, 0xe1, 0x25, 0x38, 0x27, 0x67, 0x79, 0x49, 0x7d, 0x36, 0x60, 0x43, 0x77,
	0x54, 0x17, 0xb8, 0x0d, 0x1d, 0x99, 0xf4, 0x3b, 0x03, 0x36, 0xec, 0x8e, 0x3a, 0x32, 0x09, 0xee,
	0xc3, 0x96, 0x65, 0xe9, 0x5c, 0xcd, 0xb4, 0xc0, 0xcb, 0xd0, 0x53, 0x25, 0x2d, 0x79, 0xb6, 0x6a,
	0x11, 0x6f, 0xc0, 0xce, 0x13, 0x21, 0x92, 0x47, 0x11, 0x45, 0x8d, 0x23, 0xc2, 0x86, 0xf9, 0xe3,
	0x8a, 0xd8, 0x1d, 0x55, 0xeb, 0xe0, 0x3a, 0xec, 0x2e, 0x61, 0xd6, 0x62, 0x17, 0xba, 0xba, 0xcc,
	0x2c, 0xcc, 0x2c, 0x83, 0x3d, 0xb8, 0x38, 0xa6, 0x42, 0x44, 0xd9, 0xaa, 0x5c, 0xed, 0xc8, 0xfe,
	0x3a, 0x0e, 0x01, 0x57, 0x41, 0x56, 0xec, 0x14, 0xd3, 0xdb, 0xbf, 0xbb, 0x70, 0xde, 0x9c, 0x6a,
	0x2c, 0x8a, 0x8f, 0x32, 0x16, 0xf8, 0x0c, 0x36, 0x9f, 0x0a, 0xaa, 0xce, 0x89, 0x57, 0xf8, 0x89,
	0x9b, 0xe0, 0xab, 0xa9, 0x79, 0xfe, 0xbf, 0xb6, 0x6b, 0xbb, 0xc0, 0xc1, 0xe7, 0xe0, 0x36, 0x62,
	0x87, 0xff, 0xaf, 0x36, 0x86, 0xcd, 0x26, 0x1f, 0x1c, 0xb4, 0xd0, 0x27, 0x12, 0xf6, 0xae, 0xad,
	0x41, 0x34, 0x92, 0x43, 0x86, 0xaf, 0x01, 0x96, 0x49, 0x61, 0xd0, 0x22, 0xb5, 0xb2, 0xf6, 0xf6,
	0xd6, 0x62, 0x1a, 0xe9, 0x7d, 0x86, 0x6f, 0x61, 0x7b, 0xb9, 0x73, 0x90, 0xd2, 0xad, 0xb3, 0x95,
	0xbf, 0x07, 0xae, 0x49, 0xe8, 0x71, 0x96, 0xd3, 0x27, 0xc4, 0x55, 0x16, 0xaf, 0x7a, 0xde, 0x29,
	0xbd, 0xc0, 0xf1, 0xb6, 0x7e, 0xfd, 0xdc, 0x77, 0xc3, 0x28, 0x97, 0xa1, 0x11, 0x7f, 0xf0, 0x10,
	0xa0, 0x10, 0x9a, 0x8e, 0x32, 0x55, 0xce, 0x08, 0xaf, 0xf2, 0x7a, 0x76, 0x78, 0x33, 0x3b, 0xdc,
	0xbe, 0x8b, 0x97, 0x39, 0x49, 0x35, 0xd3, 0xfd, 0xaf, 0x9f, 0x7b, 0xd5, 0x53, 0x77, 0x0d, 0xe9,
	0x85, 0xe1, 0x1c, 0xfa, 0xdf, 0xe6, 0x3e, 0x3b, 0x9e, 0xfb, 0xec, 0xc7, 0xdc, 0x67, 0x5f, 0x16,
	0xbe, 0x73, 0xbc, 0xf0, 0x9d, 0xef, 0x0b, 0xdf, 0x79, 0xb3, 0x61, 0x1c, 0x26, 0xbd, 0x4a, 0xeb,
	0xce, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x2e, 0x78, 0xdd, 0xeb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	GetTestA(ctx context.Context, in *TestARequest, opts ...grpc.CallOption) (*TestAResponse, error)
	GetTestAB(ctx context.Context, in *TestARequest, opts ...grpc.CallOption) (*TestAResponse, error)
	FeedData(ctx context.Context, opts ...grpc.CallOption) (TestService_FeedDataClient, error)
	StreamData(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (TestService_StreamDataClient, error)
	StreamDataAlt1(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (TestService_StreamDataAlt1Client, error)
	TestEmpty(ctx context.Context, in *toldata.Empty, opts ...grpc.CallOption) (*toldata.Empty, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) GetTestA(ctx context.Context, in *TestARequest, opts ...grpc.CallOption) (*TestAResponse, error) {
	out := new(TestAResponse)
	err := c.cc.Invoke(ctx, "/cdl.toldatatest.TestService/GetTestA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) GetTestAB(ctx context.Context, in *TestARequest, opts ...grpc.CallOption) (*TestAResponse, error) {
	out := new(TestAResponse)
	err := c.cc.Invoke(ctx, "/cdl.toldatatest.TestService/GetTestAB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) FeedData(ctx context.Context, opts ...grpc.CallOption) (TestService_FeedDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestService_serviceDesc.Streams[0], "/cdl.toldatatest.TestService/FeedData", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceFeedDataClient{stream}
	return x, nil
}

type TestService_FeedDataClient interface {
	Send(*FeedDataRequest) error
	CloseAndRecv() (*FeedDataResponse, error)
	grpc.ClientStream
}

type testServiceFeedDataClient struct {
	grpc.ClientStream
}

func (x *testServiceFeedDataClient) Send(m *FeedDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceFeedDataClient) CloseAndRecv() (*FeedDataResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FeedDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) StreamData(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (TestService_StreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestService_serviceDesc.Streams[1], "/cdl.toldatatest.TestService/StreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_StreamDataClient interface {
	Recv() (*StreamDataResponse, error)
	grpc.ClientStream
}

type testServiceStreamDataClient struct {
	grpc.ClientStream
}

func (x *testServiceStreamDataClient) Recv() (*StreamDataResponse, error) {
	m := new(StreamDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) StreamDataAlt1(ctx context.Context, in *StreamDataRequest, opts ...grpc.CallOption) (TestService_StreamDataAlt1Client, error) {
	stream, err := c.cc.NewStream(ctx, &_TestService_serviceDesc.Streams[2], "/cdl.toldatatest.TestService/StreamDataAlt1", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceStreamDataAlt1Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_StreamDataAlt1Client interface {
	Recv() (*StreamDataResponse, error)
	grpc.ClientStream
}

type testServiceStreamDataAlt1Client struct {
	grpc.ClientStream
}

func (x *testServiceStreamDataAlt1Client) Recv() (*StreamDataResponse, error) {
	m := new(StreamDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) TestEmpty(ctx context.Context, in *toldata.Empty, opts ...grpc.CallOption) (*toldata.Empty, error) {
	out := new(toldata.Empty)
	err := c.cc.Invoke(ctx, "/cdl.toldatatest.TestService/TestEmpty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	GetTestA(context.Context, *TestARequest) (*TestAResponse, error)
	GetTestAB(context.Context, *TestARequest) (*TestAResponse, error)
	FeedData(TestService_FeedDataServer) error
	StreamData(*StreamDataRequest, TestService_StreamDataServer) error
	StreamDataAlt1(*StreamDataRequest, TestService_StreamDataAlt1Server) error
	TestEmpty(context.Context, *toldata.Empty) (*toldata.Empty, error)
}

// UnimplementedTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (*UnimplementedTestServiceServer) GetTestA(ctx context.Context, req *TestARequest) (*TestAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestA not implemented")
}
func (*UnimplementedTestServiceServer) GetTestAB(ctx context.Context, req *TestARequest) (*TestAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestAB not implemented")
}
func (*UnimplementedTestServiceServer) FeedData(srv TestService_FeedDataServer) error {
	return status.Errorf(codes.Unimplemented, "method FeedData not implemented")
}
func (*UnimplementedTestServiceServer) StreamData(req *StreamDataRequest, srv TestService_StreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamData not implemented")
}
func (*UnimplementedTestServiceServer) StreamDataAlt1(req *StreamDataRequest, srv TestService_StreamDataAlt1Server) error {
	return status.Errorf(codes.Unimplemented, "method StreamDataAlt1 not implemented")
}
func (*UnimplementedTestServiceServer) TestEmpty(ctx context.Context, req *toldata.Empty) (*toldata.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestEmpty not implemented")
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_GetTestA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetTestA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdl.toldatatest.TestService/GetTestA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetTestA(ctx, req.(*TestARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_GetTestAB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetTestAB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdl.toldatatest.TestService/GetTestAB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetTestAB(ctx, req.(*TestARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_FeedData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).FeedData(&testServiceFeedDataServer{stream})
}

type TestService_FeedDataServer interface {
	SendAndClose(*FeedDataResponse) error
	Recv() (*FeedDataRequest, error)
	grpc.ServerStream
}

type testServiceFeedDataServer struct {
	grpc.ServerStream
}

func (x *testServiceFeedDataServer) SendAndClose(m *FeedDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceFeedDataServer) Recv() (*FeedDataRequest, error) {
	m := new(FeedDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).StreamData(m, &testServiceStreamDataServer{stream})
}

type TestService_StreamDataServer interface {
	Send(*StreamDataResponse) error
	grpc.ServerStream
}

type testServiceStreamDataServer struct {
	grpc.ServerStream
}

func (x *testServiceStreamDataServer) Send(m *StreamDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_StreamDataAlt1_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).StreamDataAlt1(m, &testServiceStreamDataAlt1Server{stream})
}

type TestService_StreamDataAlt1Server interface {
	Send(*StreamDataResponse) error
	grpc.ServerStream
}

type testServiceStreamDataAlt1Server struct {
	grpc.ServerStream
}

func (x *testServiceStreamDataAlt1Server) Send(m *StreamDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_TestEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(toldata.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdl.toldatatest.TestService/TestEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestEmpty(ctx, req.(*toldata.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdl.toldatatest.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTestA",
			Handler:    _TestService_GetTestA_Handler,
		},
		{
			MethodName: "GetTestAB",
			Handler:    _TestService_GetTestAB_Handler,
		},
		{
			MethodName: "TestEmpty",
			Handler:    _TestService_TestEmpty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FeedData",
			Handler:       _TestService_FeedData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamData",
			Handler:       _TestService_StreamData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDataAlt1",
			Handler:       _TestService_StreamDataAlt1_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "toldata_test.proto",
}

func (m *TestARequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestARequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestARequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Input) > 0 {
		i -= len(m.Input)
		copy(dAtA[i:], m.Input)
		i = encodeVarintToldataTest(dAtA, i, uint64(len(m.Input)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TestAResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestAResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestAResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Output) > 0 {
		i -= len(m.Output)
		copy(dAtA[i:], m.Output)
		i = encodeVarintToldataTest(dAtA, i, uint64(len(m.Output)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeedDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Data))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FeedDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Sum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StreamDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StreamDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != 0 {
		i = encodeVarintToldataTest(dAtA, i, uint64(m.Data))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintToldataTest(dAtA []byte, offset int, v uint64) int {
	offset -= sovToldataTest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TestARequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Input)
	if l > 0 {
		n += 1 + l + sovToldataTest(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovToldataTest(uint64(m.Id))
	}
	return n
}

func (m *TestAResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Output)
	if l > 0 {
		n += 1 + l + sovToldataTest(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovToldataTest(uint64(m.Id))
	}
	return n
}

func (m *FeedDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Data != 0 {
		n += 1 + sovToldataTest(uint64(m.Data))
	}
	return n
}

func (m *FeedDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != 0 {
		n += 1 + sovToldataTest(uint64(m.Sum))
	}
	return n
}

func (m *StreamDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovToldataTest(uint64(m.Id))
	}
	return n
}

func (m *StreamDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Data != 0 {
		n += 1 + sovToldataTest(uint64(m.Data))
	}
	return n
}

func sovToldataTest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozToldataTest(x uint64) (n int) {
	return sovToldataTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TestARequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestARequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestARequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToldataTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToldataTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Input = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TestAResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestAResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestAResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToldataTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToldataTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Output = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			m.Data = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Data |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			m.Sum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sum |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			m.Data = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Data |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToldataTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthToldataTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipToldataTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowToldataTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToldataTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthToldataTest
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthToldataTest
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowToldataTest
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipToldataTest(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthToldataTest
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthToldataTest = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowToldataTest   = fmt.Errorf("proto: integer overflow")
)
